### ISSUE TITLE
I follow your book "Rails 101" but not working.

### ISSUE THREAD

**Issue by hkftwe** [xdite/rails-101#9]
I following version was published on 2014-06-10.
First, I following the book Ch 1.0:
- gem install bootstrappers -v=4.2.1
- bootstrappers groupme

Then, Ch1.1:
- rails g model group title:string description:text

But I get result below:
/Users/MHK/Dropbox/workspace_rails/groupme/config/environments/development.rb:1:in `<top (required)>': undefined method`configure' for #Groupme::Application:0x007fefcb510960 (NoMethodError)
    from /Users/MHK/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/MHK/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in`block in require'
    from /Users/MHK/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
...
    from /Users/MHK/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in`require'
    from /Users/MHK/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.0.0/lib/rails/application.rb:189:in `require_environment!'
    from /Users/MHK/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.0.0/lib/rails/commands.rb:45:in`<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in`<main>'

**Comment by FrankFang** [comment]
+1  NoMethodError

```
~/R/groupme ❯❯❯ rails -v    
Rails 4.0.0
~/R/groupme ❯❯❯ ruby -v
ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]
```
